######################################################################
# Workflow that zip, uploads artifact and notify SNS to start pipeline.
#
######################################################################
name: 'Whoami'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/whoami.yml'
      - 'apps/whoami/**'

defaults:
  run:
    working-directory: ./apps/whoami

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        shell: bash
        run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: |
          echo ${{ steps.vars.outputs.sha_short }}
          echo ${{ steps.vars.outputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: apps/whoami/docker/Dockerfile
          push: true
          tags: |
            dniel/whoami:latest
            dniel/whoami:${{ steps.vars.outputs.branch }}
            dniel/whoami:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Zip Folder
        id: zip_and_upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        shell: bash
        run: |
          ARTIFACT_FILENAME=whoami-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}.zip
          S3_FILENAME=s3://${{ secrets.AWS_BUCKET }}/$ARTIFACT_FILENAME

          zip -r $ARTIFACT_FILENAME terraform
          aws s3 cp $ARTIFACT_FILENAME $S3_FILENAME
          echo "::set-output name=s3_filename::$S3_FILENAME"
          echo "::set-output name=artifact_filename::$ARTIFACT_FILENAME"

      - name: Uploaded file
        run: |
          echo ${{ steps.zip_and_upload.outputs.s3_filename }}
          echo ${{ steps.zip_and_upload.outputs.artifact_filename }}

      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.6
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          MESSAGE: |
            {
              "reference":"${{ steps.zip_and_upload.outputs.s3_filename }}",
              "name": "${{ steps.zip_and_upload.outputs.artifact_filename }}",
              "sha_short": "${{ steps.vars.outputs.sha_short }}",
              "branch": "${{ steps.vars.outputs.branch }}"
            }
          TOPIC_ARN: ${{ secrets.TOPIC_ARN }}
